DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       USERNAME VARCHAR(100) NOT NULL UNIQUE,
                       PASSWORD VARCHAR(255) NOT NULL,
                       ROLE VARCHAR(20) NOT NULL,
                       ENABLED BOOLEAN NOT NULL
);

CREATE TABLE CUSTOMER (
                          ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          NAME VARCHAR(150) NOT NULL,
                          EMAIL VARCHAR(150) NOT NULL
);

CREATE TABLE PRODUCT (
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         NAME VARCHAR(200) NOT NULL,
                         CARD_GAME VARCHAR(50) NOT NULL,
                         CATEGORY VARCHAR(50) NOT NULL,
                         PRICE DECIMAL(10,2) NOT NULL,
                         STOCK INT NOT NULL,
                         STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE ORDERS (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        CUSTOMER_ID BIGINT NOT NULL,
                        CUSTOMER_NAME VARCHAR(150) NOT NULL,
                        CREATED_AT TIMESTAMP NOT NULL,
                        STATUS VARCHAR(30) NOT NULL,
                        TOTAL DECIMAL(10,2) NOT NULL
);

CREATE TABLE ORDER_ITEM (
                            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ORDER_ID BIGINT NOT NULL,
                            ORDERS_KEY INT NOT NULL,
                            PRODUCT_ID BIGINT NOT NULL,
                            PRODUCT_NAME VARCHAR(200) NOT NULL,
                            UNIT_PRICE DECIMAL(10,2) NOT NULL,
                            QUANTITY INT NOT NULL,
                            SUBTOTAL DECIMAL(10,2) NOT NULL,
                            CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);